# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: main
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
